# Generated by Django 3.2.15 on 2022-11-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
